### ISSUE TITLE
error when install by $ go get github.com/hjdr4/docker-volume-glusterfs

### ISSUE THREAD

**Issue by davidkhala** [hjdr4/docker-volume-glusterfs#1]
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:89: undefined: volume.Response
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:89: undefined: volume.Request
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:97: undefined: volume.Response
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:97: undefined: volume.Request
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:106: undefined: volume.Response
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:106: undefined: volume.Request
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:110: undefined: volume.Response
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:145: undefined: volume.Response
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:165: undefined: volume.Response
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:165: undefined: volume.Request
go/src/github.com/hjdr4/docker-volume-glusterfs/driver.go:165: too many errors

**Comment by hjdr4** [comment]
Thank you for the report.
I have updated a bunch of stuff.
Should work correctly now.

**Comment by hjdr4** [comment]
I'm closing this issue. Let me know if you still have troubles.
